### ISSUE TITLE
CMakeLists.txt needs updated path for headers

### ISSUE THREAD

**Issue by taranu** [ICRAR/libprofit#3]
I believe that the paths to profit/common.h ... profit/utils.h need to be updated to include/profit/common.h in CMakeLists.txt, otherwise installing the headers will fail.

**Comment by rtobar** [comment]
Ooops, sorry about that, I forgot to update those, I'll fix this now. I also realized Travis doesn't include a "make install" step, which is probably why this wasn't caught before, I'll add this to avoid installation failures in the future.

**Comment by rtobar** [comment]
Fixed
